NB_COLUMN_CLOCKS = 8
ANIMATION_TIME = 11000  # milliseconds
CLOCK_MAX_SIZE = 130
CLOCK_PADDING = 3
GLOBAL_PADDING_CLOCK = 30
GLOBAL_PADDING_MOBILE_CLOCK = 50

# Colors
CLOCK_BACKGROUND_COLOR = "#141414"
NEEDLE_BACKGROUND_COLOR = "#c9c9c9"
BACKGROUND_COLOR = "#e8e8e8"

# Animation timing
ANIMATION_START_TIMING = "cubic-bezier(.27,0,.31,.41)"
ANIMATION_END_TIMING = "cubic-bezier(.9,.8,.62,.83)"
ANIMATION_DEFAULT_TIMING = "linear"
ANIMATION_TIMING_CONFIG = {
    "start": ANIMATION_START_TIMING,
    "end": ANIMATION_END_TIMING,
}

# Animation delay
ANIMATION_DELAY = 300  # milliseconds 